### ISSUE TITLE
Optional Quantity Slider to show total ingredients based on slider value

### ISSUE THREAD

**Issue by ajklotz** [raiguard/RecipeBook#119]
#### Is your feature request related to a problem? Please describe.

The recipe shows how many ingredients are needed to produce 1 selected item. When I am looking to see how many total ingredients I need for X amount of items, I have to multiply each ingredient to see how many I'll need. 

#### Describe the solution you'd like

A slider bar to change the total ingredient amount based on how many items I need from that recipe

#### Additional context

Optional setting that can be configured in the GUI.

**Comment by raiguard** [comment]
I don't feel that this is in scope for Recipe Book. You can use Rate Calculator to get that information.

**Comment by nihilistzsche** [comment]
I think that would be better served by a mod like helmod or factoryplanner.

**Comment by raiguard** [comment]
I see, I did misunderstand what you were saying originally. However, I still don't think this really fits in Recipe Book. The displayed information is all static information, and adding this would be difficult for implementation-related reasons. Sorry.
