### ISSUE TITLE
Crash when clicking concrete in the search box

### ISSUE THREAD

**Issue by Marwes** [raiguard/RecipeBook#120]
#### Describe the Bug

After searching for "Concrete" and clicking on it RecipeBook crashes due to a nil reference.

I had removed some mods (AAI-vehicle suite) shortly beforehand so that might have something to do with it. As a workaround-fix, refreshing recipe book via `/rb-refresh-all` fixes the issue.

#### To Reproduce

1. Search for "Concrete" in RecipeBook
2. Click on "Concrete"
5. See error

```
The mod Recipe Book (3.5.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_gui_click (ID 1)
__RecipeBook__/scripts/gui/info/list-box.lua:84: bad argument #1 of 2 to 'lower' (string expected, got nil)
stack traceback:
	[C]: in function 'lower'
	__RecipeBook__/scripts/gui/info/list-box.lua:84: in function 'update'
	__RecipeBook__/scripts/gui/info/index.lua:328: in function 'update_contents'
	__RecipeBook__/scripts/gui/info/index.lua:606: in function 'build'
	__RecipeBook__/control.lua:43: in function 'OPEN_PAGE'
	__RecipeBook__/scripts/gui/search/actions.lua:358: in function '?'
	__RecipeBook__/scripts/gui/search/index.lua:41: in function 'dispatch'
	__RecipeBook__/control.lua:295: in function 'handle_gui_action'
	__RecipeBook__/control.lua:302: in function 'read_gui_action'
	__RecipeBook__/control.lua:312: in function <__RecipeBook__/control.lua:310>
```

#### Save file & Username

[Island Pyanodon regenerated 2.zip](https://github.com/raiguard/RecipeBook/files/10849517/Island.Pyanodon.regenerated.2.zip)

#### Log file

[factorio-current.log](https://github.com/raiguard/RecipeBook/files/10849529/factorio-current.log)

**Comment by raiguard** [comment]
Thanks for the report. Considering that the command fixed the issue, this appears to have happened when your database got corrupted. I am completely rewriting this mod to reduce complexity so this shouldn't be an issue once the rewrite is complete.
