### ISSUE TITLE
Option to go to the root

### ISSUE THREAD

**Issue by Layarion** [raiguard/RecipeBook#121]
#### Is your feature request related to a problem? Please describe.

It's frusterating to drag the box over my black potions mall, only to have it tell me "you need more steel"...then i add more steel and i do it again and it says "you need more iron now". like, i wish it factored in what the steel would need on the first pass.

#### Describe the solution you'd like

Basically it would be nice, if i could just ClickDrag over a single potion factory, and the calculator just pulls up _everything_ i'll need to support that factory. all the way back to the miners and how many of each.

**Comment by raiguard** [comment]
Was this meant for rate calculator? Recipe Book doesn't have any features like this.

Regardless, what you ask for is completely non trivial and it's a very difficult math problem. Rate calculator is meant to tell you what you have built, not what you need to build. You will need to use a planner mod (Factory Planner) or website (FactorioLab) to plan builds in advance.

**Comment by Layarion** [comment]
Yes, not sure how i ended up here...sorry
