### ISSUE TITLE
Searching for "seed" causes mod crash

### ISSUE THREAD

**Issue by SophieFitz** [raiguard/RecipeBook#125]
#### Describe the Bug

I typed the word "seed" into Recipe Book's main search bar and it crashed immediately.

#### To Reproduce

Load the save file I've attached.
Open Recipe Book and search for "seed". It will proceed to crash.

#### Save file & Username

[Seablock playground.zip](https://github.com/raiguard/RecipeBook/files/11591209/Seablock.playground.zip)

My in-game username is SophieFitz

#### Log file

[factorio-current.log](https://github.com/raiguard/RecipeBook/files/11591219/factorio-current.log)

**Comment by SophieFitz** [comment]
I disabled "fuzzy search" and that stopped the crash. Still an issue

**Comment by SophieFitz** [comment]
The flib fix you just pushed fixed this issue! Thank you

**Comment by raiguard** [comment]
Oh sweet! Thanks for the report.
