### ISSUE TITLE
Temporary Train stop can not be created while Recipe Book is open

### ISSUE THREAD

**Issue by ChaosSaber** [raiguard/RecipeBook#134]
### Description

If you are sitting in a train and open the map, you can add temporary train stops via Ctrl + left mouse button click on a track. If the Recipe Book Gui is open, this no longer works

### Reproduction

1. Enter train
2. Open Recipe Book
3. Open map view
4. Try to set a temporary stop with Ctrl + LMB on a track
5. Nothing happens

**Comment by raiguard** [comment]
This is a vanilla behavior - it will only set the train stop if there are no GUIs set as opened. The same thing happens if you open the player inventory GUI, or any other built-in GUI.

To work around it, you can click the "keep open" button in recipe book so it will un-mark itself as "opened".

**Comment by ChaosSaber** [comment]
That is good to know. Actually never tried it with another GUI as they usually obscure the whole screen.
Thanks for the info.
