### ISSUE TITLE
Crash in RecipeBook::on_gui_checked_state_changed

### ISSUE THREAD

**Issue by moxian** [raiguard/RecipeBook#136]
### Description

Was playing a game with Space Exploration + Krastorio + Recipe Book (and no other mods). Multiplayer with just me being online on the server at the time.

Browsing the recipes for wood (well, Mineral water > Nitric Acid > Fertilizer > Wood). Noticed that there is a lot of "mined from <tree species>" entries that i didn't care about, and decided to collapse. Went to Settings > Categories > Entity type > unchecked the Tree > immediately got a crash.

![image](https://github.com/raiguard/RecipeBook/assets/7831163/37d7afdf-4124-4501-a5a6-bc112d831451)

I thought this is due to a bunch of tree and tree-related recipe windows being open at the time, and unticking the checkbox failing to update them properly. However I tried to reproduce it locally, following (roungly) the same steps, and didn't get it to crash, so I'm not sure now...

Savefile: [dex2.zip](https://github.com/raiguard/RecipeBook/files/12413071/dex2.zip)

### Reproduction

Unknown. Feel free to close the bugreport as invalid.

**Comment by raiguard** [comment]
I couldn't reproduce it, but I have theoretically fixed the cause of the crash. Thanks for the report!
