### ISSUE TITLE
RecipeBook window does not close on ESC when it's a window opened with ALT-click

### ISSUE THREAD

**Issue by Soul-Burn** [raiguard/RecipeBook#137]
### Description

When opening a window with ALT-click, it does not close when press ESC, requiring clicking the X in the corner.

This behavior is different than when opening the main window with ctrl-B. That window closes on ESC unless pinned.

### Reproduction

1. ALT-click some entity in the world
2. Press ESC

Expected: Window closes
Actual: Main menu opens

**Comment by raiguard** [comment]
This is intentional.
