### ISSUE TITLE
Modifying Technologies Causing Incompatibility Issue

### ISSUE THREAD

**Issue by luaotix** [raiguard/RecipeBook#138]
### Description

I created a mod to make Nullius compatible with some other mods I need. I made changes to both technologies and recipes, but now I'm unable to load my save file. Here are the specific crash details:

Error while running event RecipeBook::on_load()
__RecipeBook__/scripts/database/technology.lua:68: attempt to index local 'recipe_data' (a nil value)
stack traceback:
	__RecipeBook__/scripts/database/technology.lua:68: in function 'technology'
	__RecipeBook__/scripts/database.lua:72: in function 'build'
	__RecipeBook__/control.lua:196: in function <__RecipeBook__/control.lua:191>

**Comment by raiguard** [comment]
If you change prototypes without changing mod versions, RB doesn't work. This is a known issue and is unfixable in 3.x. Recipe Book 4 will not have these problems.
