### ISSUE TITLE
Feature Idea: Copy icon rich text in clickboard on right click

### ISSUE THREAD

**Issue by Spook2U** [raiguard/RecipeBook#139]
While hovering anything, when the right mouse button (or another shortcut) is pressed, the according rich text is copied in the clipboard to represent the according icon.

For example, when I right-click the Iron Plate product it would copy: "[item=iron-plate]" in my clipboard. 
This would be particularly helpful when using mod packs where the internal names are new / difficult (For example AngleBob: angel-ore6)

**Comment by raiguard** [comment]
Unfortunately, mods cannot write to the clipboard.
