### ISSUE TITLE
When making new groups it will fail on map load

### ISSUE THREAD

**Issue by PigStyle101** [raiguard/RecipeBook#140]
### Description

When i added a new group to my modpack recipe book would fail on load tell i disabled the mod re-save the save file and then enabled the mod again and reloaded the save.

The mod Recipe Book (3.5.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_load()
__RecipeBook__/scripts/database/item.lua:17: attempt to index local 'group_data' (a nil value)
stack traceback:
	__RecipeBook__/scripts/database/item.lua:17: in function <__RecipeBook__/scripts/database/item.lua:7>
	(...tail calls...)
	__RecipeBook__/scripts/database.lua:65: in function 'build'
	__RecipeBook__/control.lua:196: in function <__RecipeBook__/control.lua:191>

### Reproduction

This is happening in a dev environment, so the mod is not on the portal as it is being adjusted. I don't know if this will persist after i push my mod update, but if it does ill send you the save file and set recipe book to be incompatible tell its good to go.

Thanks.

**Comment by raiguard** [comment]
Changing mod contents without changing mod versions will cause crashes in Recipe Book 3. This is unfixable in 3.x, but 4.x will not have this issue.
