### ISSUE TITLE
Feature Request: Show raw costs

### ISSUE THREAD

**Issue by Sipke82** [raiguard/RecipeBook#141]
In order to get a better understanding how expensive some items are, it would be great to see the raw costs of items. even the factorio Wiki is somewhat limited look for example Spidertron:
![image](https://github.com/raiguard/RecipeBook/assets/30873812/ce891e29-1955-473a-ba57-10a21e69b264)

We still dont know how much raw materials were needed for the processing units. so it would take quite some additional calculations to get too those real raw costs.

**Comment by raiguard** [comment]
Unfortunately, this isn't at all feasible. Not only would calculating this take a lot of time (there isn't a convenient function in the API to do it), but it falls over as soon as multiple possible ingredients are involved.
