### ISSUE TITLE
Feature request: Hotkey to open quick reference from crafting menu

### ISSUE THREAD

**Issue by Bulletti** [raiguard/RecipeBook#142]
I would love a hotkey like Mouse3 or Shift + Mouse3 to open the quick ref directly, saving my ADHD jumbled brain one click. It's not a lot to click one more time, but it feels insurmountable at certain times and moods. Please? I tried looking at your code, but I don't know how to add it myself, since I really doubt it would work if I just added it to custom-input as rb-quick-ref. (Just tried that, didn't work.)

**Comment by raiguard** [comment]
I'm not adding any more features to Recipe Book 3 because I'm currently working on Recipe Book 4. I'm not sure what recipe quick reference will look like in RB4 quite yet but I'll keep this in mind.
