### ISSUE TITLE
Display the degree of unresearch-edness for unresearched items

### ISSUE THREAD

**Issue by gparker42** [raiguard/RecipeBook#146]
I'm working on a display of unresearch-edness for unresearched items. Any interest?

The idea: for large mods, unresearched objects that are very far away should be distinguishable from unresearched objects that will be available sooner.

My current scheme color-codes unresearched objects.
yellow: objects that are unresearched, but all of the required research ingredients are unlocked.
orange: objects that are unresearched, and one of the required research ingredients is also unresearched.
red: objects that are unresearched, and two or more of the required research ingredients are unresearched.

Secondly, ingredients_in and products_of are also sorted by research difficulty. In this case they're simply sorted by #recipe.science_packs on the assumption that more science packs is more difficult.

![moltensalt](https://github.com/raiguard/RecipeBook/assets/992218/1a2c66b9-8d11-44ad-8de5-b7cde06c2605)

**Comment by raiguard** [comment]
I'm not sure I'm a fan of this feature. Regardless, I'm not adding any more features to Recipe Book 3 because I'm currently working on Recipe Book 4. Feel free to make a personal fork though!
