### ISSUE TITLE
Crashed twice same error

### ISSUE THREAD

**Issue by BigglesOf266** [raiguard/RecipeBook#147]
Running own headless server under debian. Main mods were Space Exploration and Krastorio. There are a number of others including LTN
Connecting from Win 11 PC. Only player on at the time. Searching recipe book for rocket fuel and client ceased responding

factorio-current.log from server contains:
 585.029 Error MainLoop.cpp:1391: Exception at tick 4300452: The mod Recipe Book (3.5.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_gui_click (ID 1)
__RecipeBook__/scripts/formatter.lua:60: attempt to concatenate local 'inner' (a nil value)
stack traceback:
        __RecipeBook__/scripts/formatter.lua:60: in function 'rich_text'
        __RecipeBook__/scripts/formatter.lua:276: in function 'get_base_tooltip'
        __RecipeBook__/scripts/formatter.lua:566: in function <__RecipeBook__/scripts/formatter.lua:534>
        (...tail calls...)
        __RecipeBook__/scripts/formatter.lua:120: in function '?'
        __RecipeBook__/scripts/formatter.lua:350: in function 'get_tooltip_deets'
        __RecipeBook__/scripts/formatter.lua:582: in function <__RecipeBook__/scripts/formatter.lua:534>
        (...tail calls...)
        __RecipeBook__/scripts/gui/info/list-box.lua:95: in function 'update'
        __RecipeBook__/scripts/gui/info/index.lua:328: in function 'update_contents'
        __RecipeBook__/scripts/gui/info/index.lua:606: in function 'build'
        __RecipeBook__/control.lua:43: in function 'OPEN_PAGE'
        __RecipeBook__/scripts/gui/search/actions.lua:358: in function '?'
        __RecipeBook__/scripts/gui/search/index.lua:41: in function 'dispatch'
        __RecipeBook__/control.lua:298: in function 'handle_gui_action'
        __RecipeBook__/control.lua:305: in function 'read_gui_action'
        __RecipeBook__/control.lua:315: in function <__RecipeBook__/control.lua:313>
 585.030 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Recipe Book (3.5.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_gui_click (ID 1)
__RecipeBook__/scripts/formatter.lua:60: attempt to concatenate local 'inner' (a nil value)
stack traceback:
        __RecipeBook__/scripts/formatter.lua:60: in function 'rich_text'
        __RecipeBook__/scripts/formatter.lua:276: in function 'get_base_tooltip'
        __RecipeBook__/scripts/formatter.lua:566: in function <__RecipeBook__/scripts/formatter.lua:534>
        (...tail calls...)
        __RecipeBook__/scripts/formatter.lua:120: in function '?'
        __RecipeBook__/scripts/formatter.lua:350: in function 'get_tooltip_deets'
        __RecipeBook__/scripts/formatter.lua:582: in function <__RecipeBook__/scripts/formatter.lua:534>
        (...tail calls...)
        __RecipeBook__/scripts/gui/info/list-box.lua:95: in function 'update'
        __RecipeBook__/scripts/gui/info/index.lua:328: in function 'update_contents'
        __RecipeBook__/scripts/gui/info/index.lua:606: in function 'build'
        __RecipeBook__/control.lua:43: in function 'OPEN_PAGE'
        __RecipeBook__/scripts/gui/search/actions.lua:358: in function '?'
        __RecipeBook__/scripts/gui/search/index.lua:41: in function 'dispatch'
        __RecipeBook__/control.lua:298: in function 'handle_gui_action'
        __RecipeBook__/control.lua:305: in function 'read_gui_action'
        __RecipeBook__/control.lua:315: in function <__RecipeBook__/control.lua:313>"
 585.030 Info ServerMultiplayerManager.cpp:814: updateTick(4300452) changing state from(InGame) to(Failed)

**Comment by raiguard** [comment]
Please send me the save file, I am unable to reproduce.

**Comment by BigglesOf266** [comment]
[_autosave4.zip](https://github.com/raiguard/RecipeBook/files/13454611/_autosave4.zip)
Hello Is this what you are asking for ? Its the save file I restore to each time it has crashed. The game is up and running after I reverted back to the previous version of the recipe book 3.5.5

**Comment by BigglesOf266** [comment]
[mod-list.json](https://github.com/raiguard/RecipeBook/files/13454634/mod-list.json)
Also Mod-list
