### ISSUE TITLE
Detail view stops working

### ISSUE THREAD

**Issue by alethiophile** [raiguard/RecipeBook#150]
Occasionally, Recipe Book gets into a state where the detail view stops being updated when clicking in the search pane.

Searching still works; the back/forward buttons in the detail view still work, if the detail view is already shown; however, clicking on the entries in the search pane does nothing (neither brings up the detail view if hidden, nor updates it if shown). The only way I've found to make it work again is to restart the game. (Saving and reloading without restarting the game does not fix the issue.) I haven't found any specific trigger that makes the issue appear; it happens unpredictably, on opening Recipe Book with the keyboard shortcut, some varying time after loading the save.

I'm using Recipe Book 3.5.7 on Factorio 1.1.100.

**Comment by alethiophile** [comment]
Update: it appears that when this issue occurs, it also affects similar GUI components in other mods (I saw it in Factory Planner as well). So this may be a Factorio-side issue rather than in the mod.

**Comment by raiguard** [comment]
If you can consistently reproduce it please let me know, this sounds like a spicy bug!
