### ISSUE TITLE
Ability to change window size/scaling

### ISSUE THREAD

**Issue by xizar** [raiguard/RecipeBook#151]
When increasing game scale, the GUI helpfully scales along with it, however at larger magnification sizes (anything above 150% UI scaling) the Recipebook's GUI will span the entire vertical length of the game screen.

Additionally, the settings page does not adjust its size and extends off-screen at 200% scaling and above.

It would be nice if the length of the window were adjustable (number of visible rows before needing to scroll?) could be changed.

Due to a need for some people with poor vision to play with larger UI scaling levels, simply playing at lower UI-scales is a poor kludge.

**Comment by raiguard** [comment]
Recipe Book 4 will have a constrained height, so this won't be an issue any more.
