### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SGZ-Creations** [raiguard/RecipeBook#152]
The mod Recipe Book (3.5.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::Custom event (ID 392)
__RecipeBook__/scripts/formatter.lua:60: attempt to concatenate local 'inner' (a nil value)
stack traceback:
	__RecipeBook__/scripts/formatter.lua:60: in function 'rich_text'
	__RecipeBook__/scripts/formatter.lua:276: in function 'get_base_tooltip'
	__RecipeBook__/scripts/formatter.lua:566: in function <__RecipeBook__/scripts/formatter.lua:534>
	(...tail calls...)
	__RecipeBook__/scripts/gui/search/index.lua:161: in function 'update_visual_contents'
	__RecipeBook__/scripts/gui/search/index.lua:504: in function 'build'
	__RecipeBook__/control.lua:255: in function <__RecipeBook__/control.lua:240>
	[C]: in function 'raise_event'
	__flib__/dictionary-lite.lua:366: in function <__flib__/dictionary-lite.lua:314>
stack traceback:
	[C]: in function 'raise_event'
	__flib__/dictionary-lite.lua:366: in function <__flib__/dictionary-lite.lua:314>

**Comment by Diablo-D3** [comment]
I am, too, getting this exact error.

This is happening on an otherwise normal Pyblock + Pyhardmode game, but also has Factory Planner.

**Comment by raiguard** [comment]
Please send me a save file with exact reproduction steps. I have never been able to reproduce this bug.

**Comment by Diablo-D3** [comment]
Unfortunately, I ended up fixing this by removing the mod, server saving, reinstalling the mod, and now the problem is gone. Also, it did not effect all players in a multiplayer game. So, I couldn't reproduce it for me, but another player could for them; them merely joining triggered the problem.

**Comment by SGZ-Creations** [comment]
I don't have a save. I Do have an idea to how it happen
1. Install mods using the Lib: Recipe book, LTN, maybe others.
2 Then create a save like normal. 
3 Save that as normal.
4. Start that save again.
4 Re save while it's the translation is running and exit save. 
5 Then re open save let it load Translation to end. Where the crash should occur.

**Comment by raiguard** [comment]
Fixed for the next version of flib.
