### ISSUE TITLE
Language mixing

### ISSUE THREAD

**Issue by phooenixdassmatte** [raiguard/RecipeBook#153]
I loaded an old save and accidently had my native language swedish on in options while loading that save, so when your mod remade the recipe list it used swedish words, and now i switched to english because that's what i want to use. But now i get some items in swedish and some in english in the recipe book. Is there a way to recalculate the recipe book?

Sure it's a little funny when trying to read fartmodul when you're expecting to read an english word (speedmodule) but i can see that it could be confusions.

**Comment by raiguard** [comment]
There is no way for me to detect when your language changes in single player, so run the `/rb-refresh-all` command to rebuild the database and retranslate everything.

**Comment by phooenixdassmatte** [comment]
Nice that worked, thanks!
