### ISSUE TITLE
Feature Request: Add Entity Energy Usage

### ISSUE THREAD

**Issue by naterarmstrong** [raiguard/RecipeBook#155]
This mod is amazing, but the one thing that is missing for me on buildings is the amount of energy that they take while in use.

In particular, I ran into this when looking for machines in early-game seablock, where power usage is a pretty important aspect of a building.

**Comment by raiguard** [comment]
Recipe Book 4 will feature all of the information that is shown in game tooltips. This will be shown in the info panes as well (but hasn't been implemented quite yet).
![image](https://github.com/raiguard/RecipeBook/assets/3515394/abea03d3-fa43-424a-9f63-2961a13f6f02)
