### ISSUE TITLE
Factorio mods localization - feedback

### ISSUE THREAD

**Issue by dima74** [raiguard/RecipeBook#158]
Hi @raiguard! I noticed you recently uninstalled [factorio-mods-localization](https://github.com/dima74/factorio-mods-localization). If possible, could you please provide some feedback, maybe something that could be improved? Thanks!

**Comment by raiguard** [comment]
Hey, my including the mod in that project was a complete accident. I have my [own Crowdin project](https://crowdin.com/project/raiguards-factorio-mods) with my [own script](https://github.com/raiguard/factorio-development-tools/blob/main/factorio-crowdin-sync) to sync as a part of my release workflow.

The primary thing that kept me from simply using your project is that your project makes PRs / commits every week. There is no way for me to "pull" translations as a part of my release workflow. If you could add a way to do that then I might ditch my janky in-house solution in favor of your much more battle-tested solution.

Thanks!

**Comment by dima74** [comment]
Thanks for the feedback! I added option to do this, please see ["Disable weekly updates from Crowdin" section](https://github.com/dima74/factorio-mods-localization?tab=readme-ov-file#disable-weekly-updates-from-crowdin)

**Comment by raiguard** [comment]
Thank you! I will take a look at that and see if I can integrate it into my workflow.

**Comment by raiguard** [comment]
I have taken a look at it, and while it is an improvement, there are still a few fundamental issues:
* Running it manually pushes a commit to the repository. I would like to pull the translations into my local clone instead.
* The project is a GitHub app, locking me into this platform, which I do not like.

I appreciate your effort (seriously, thank you for your work, it's amazing!), but it's just not for me. Accommodating my requests would probably require a lot more work than it's worth. I'll continue using my own solution.

Thanks!
