### ISSUE TITLE
Crash on loading save - RecipeBook::on_load()

### ISSUE THREAD

**Issue by Atlntssplayer** [raiguard/RecipeBook#160]
Hi

I got this error on loading a save:

The mod Recipe Book (3.5.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_load()
__RecipeBook__/scripts/database/technology.lua:68: attempt to index local 'recipe_data' (a nil value)
stack traceback:
	__RecipeBook__/scripts/database/technology.lua:68: in function 'technology'
	__RecipeBook__/scripts/database.lua:73: in function 'build'
	__RecipeBook__/control.lua:196: in function <__RecipeBook__/control.lua:191>

thx for this great mod

**Comment by raiguard** [comment]
This happened because you changed mod contents without changing mod versions, leading to an invalid database state. This is unfixable in the current version but no longer happens in the 4.0 rewrite.
