### ISSUE TITLE
Crash on player join

### ISSUE THREAD

**Issue by FKuerten** [raiguard/RecipeBook#161]
A third player joined.
I do not recall if the mod was still "translating".

> The mod Recipe Book (3.5.7) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event RecipeBook::Custom event (ID 270)
> __RecipeBook__/scripts/formatter.lua:60: attempt to concatenate local 'inner' (a nil value)
> stack traceback:
> 	__RecipeBook__/scripts/formatter.lua:60: in function 'rich_text'
> 	__RecipeBook__/scripts/formatter.lua:276: in function 'get_base_tooltip'
> 	__RecipeBook__/scripts/formatter.lua:566: in function <__RecipeBook__/scripts/formatter.lua:534>
> 	(...tail calls...)
> 	__RecipeBook__/scripts/gui/util.lua:88: in function 'update_list_box'
> 	__RecipeBook__/scripts/gui/search/index.lua:258: in function 'update_history'
> 	__RecipeBook__/scripts/gui/search/index.lua:501: in function 'build'
> 	__RecipeBook__/control.lua:255: in function <__RecipeBook__/control.lua:240>
> 	[C]: in function 'raise_event'
> 	__flib__/dictionary-lite.lua:372: in function <__flib__/dictionary-lite.lua:354>
> stack traceback:
> 	[C]: in function 'raise_event'
> 	__flib__/dictionary-lite.lua:372: in function <__flib__/dictionary-lite.lua:354>

**Comment by raiguard** [comment]
This should have been fixed in the latest version of flib (Factorio Library).
