### ISSUE TITLE
Mod doesn´t show up in the Manage Tab

### ISSUE THREAD

**Issue by theProdigy246** [raiguard/RecipeBook#163]
i am currently on mod version 3.5.8, and the mod doesnt show up under the manage tab when it is installed.
i tried manually deleting it out of the mod folder and reinstalling, but it didn´t fix this, is their possibly an error with the info.json?

**Comment by raiguard** [comment]
It works just fine for me and thousands of others, something must be weird with your setup. The Factorio log should give you more info.
