### ISSUE TITLE
Error when loading a savegame after editing some mod recipes

### ISSUE THREAD

**Issue by Schmitt-DE** [raiguard/RecipeBook#165]
The following error happened after loading a savegame directly after editing another mods recipes.

 394.180 Error AppManagerStates.cpp:1659: The mod Recipe Book (3.5.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_load()
__RecipeBook__/scripts/database/technology.lua:68: attempt to index local 'recipe_data' (a nil value)
stack traceback:
	__RecipeBook__/scripts/database/technology.lua:68: in function 'technology'
	__RecipeBook__/scripts/database.lua:73: in function 'build'
	__RecipeBook__/control.lua:196: in function <__RecipeBook__/control.lua:191>

**Comment by raiguard** [comment]
This is a known issue, and cannot be fixed in the current version. The 4.0 rewrite will not have this problem.
