### ISSUE TITLE
crash while loading 3.5.8 save with 3.5.9

### ISSUE THREAD

**Issue by Teji85** [raiguard/RecipeBook#167]
getting a crash when loading a save after updateing to 3.5.9

The mod Recipe Book (3.5.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_configuration_changed
__RecipeBook__/scripts/database.lua:106: attempt to index field 'item' (a nil value)
stack traceback:
	__RecipeBook__/scripts/database.lua:106: in function 'update_launch_products'
	__RecipeBook__/scripts/database.lua:148: in function 'handle_research_updated'
	__RecipeBook__/scripts/database.lua:99: in function 'check_force'
	__RecipeBook__/scripts/database.lua:89: in function 'new'
	__RecipeBook__/control.lua:221: in function 'generic_handler'
	__flib__/migration.lua:111: in function <__flib__/migration.lua:109>

**Comment by raiguard** [comment]
Can you post your save file?

**Comment by raiguard** [comment]
Nevermind, I got it.
